### PR TITLE
MiP library changes

### PR DESCRIPTION
**Pull request by chris-mottram**
Hi, I liked your library, but wanted to do more with my MiP. So I forked your code and added various new API to your library, along with quite a lot of test programs. I've also managed to figure out how to read data back out of gatttool, so the library can retrieve telemetry from MiP. Anyway, feel free to take or merge any code you are interested in into your repository. I've not done a Pull Request before, I followed the examples:
https://help.github.com/articles/fork-a-repo/
and
https://help.github.com/articles/using-pull-requests/

Hope thats OK...

cheers

Chris

### CODE REVIEW

**Comment by vlimit** [comment]
Hey. Thanks! I've picked up the changes. Haven't looked through them yet, but I hadn't done anything with the code and you've added a lot of functionality. I'd been hoping to spend a lot more time on this, but got sidetracked on some other stuff.

Cheers,
Stu

**Comment by chris-mottram** [comment]
Excellent - hope you find them useful. I'm still working on some changes to the update loop in mip_explorer_gui to smooth continuous drive mode so that may get updated at some point. My MiP is actually at work at the moment so this depends on me having a quiet evening at work at some point...

cheers

Chris

**Comment by vlimit** [comment]
Hi Chris,

Well, it wasn't much of a library. I've merged your code. Thanks for the 
changes. Haven't had much time to go through it yet. Python had a moan 
about your non-ascii dashes, so I've fixed that.

I got a bit distracted at the end of last year with integrating MIP with 
ROS and deciding that I need to add a compass to MIP. Knowing that this 
has been useful to someone is pretty motivating :).

Andy added this last month:

https://github.com/WowWeeLabs/MiP-BLE-Protocol/blob/master/MiP-with-UART.md

You've probably already come across it but just in case, it's worth 
looking at this:

https://github.com/hybridgroup/cylon-mip

Cheers,
Stu
devel@rachandstu.com

**Comment by chris-mottram** [comment]
Stuart Warren wrote:

> Hi Chris,
> 
> Well, it wasn't much of a library. I've merged your code. Thanks for the 
> changes. Haven't had much time to go through it yet. Python had a moan 
> about your non-ascii dashes, so I've fixed that.

How odd, not sure how I managed that. I probably copied the comment from 
the protocol document, perhaps my browser rendering that uses the wrong 
dashes.

> I got a bit distracted at the end of last year with integrating MIP with 
> ROS and deciding that I need to add a compass to MIP. Knowing that this 
> has been useful to someone is pretty motivating :).

Sounds cool - what's "ROS" though?

I was hoping to write a client-side based improved 'roam mode' with 
telemetry to allow him to map rooms etc - though I got sidetracked 
writing a GUI to enable a simple remote teleprescense - I currently have 
one of these:
http://www.amazon.co.uk/gp/product/B00KKJ66JK?psc=1&redirect=true&ref_=oh_aui_detailpage_o08_s00
bluetacked to his head so I can operate him remotely...

> Andy added this last month:
> 
> https://github.com/WowWeeLabs/MiP-BLE-Protocol/blob/master/MiP-with-UART.md
> 
> I'd not seen that before - thanks! I had seen the SparkFUN board - but 
> didn't fancy taking a saw to my MiP! Giving MiP a WiFi connection rather 
> than the (rather limited range) BLE connection could be useful...
> 
> You've probably already come across it but just in case, it's worth 
> looking at this:
> 
> https://github.com/hybridgroup/cylon-mip

Yes I saw that,but couldn't get it to install on most of my computers 
due to dependency problems - most of my computers run older OS's due to 
the hardware I have to talk to. I then saw your library, and was meaning 
to learn some python at some point, so job done! I found I could upgrade 
a spare raspberry pi with the latest bluez library to get BLE support, 
so thats used for development...

cheers

Chris

> Cheers,
> Stu
> devel@rachandstu.com
> 
> On 27/02/15 23:14, Chris Mottram wrote:
> 
> > Hi, I liked your library, but wanted to do more with my MiP. So I 
> > forked your code and added various new API to your library, along with 
> > quite a lot of test programs. I've also managed to figure out how to 
> > read data back out of gatttool, so the library can retrieve telemetry 
> > from MiP. Anyway, feel free to take or merge any code you are 
> > interested in into your repository. I've not done a Pull Request 
> > before, I followed the examples:
> > https://help.github.com/articles/fork-a-repo/
> > and
> > https://help.github.com/articles/using-pull-requests/
> > 
> > Hope thats OK...
> > 
> > cheers
> > 
> > Chris
> > 
> > ---
> > 
> > ```
> >     You can view, comment on, or merge this pull request online at:
> > ```
> > 
> > https://github.com/vlimit/mip/pull/1
> > 
> > ```
> >     Commit Summary
> > ```
> > - First update to vlimits original code. Added charReadReply to read
> >   notifications from mip back to the client. Added continuous drive
> >   methods
> >   stopDrive/continuousDriveForward/continuousTurnRight/continuousTurnLeft/continuousDriveBackward.
> >   continuousTurnRight/continuousTurnLeft not working yet. Added
> >   setChestLed / getChestLed / getBatteryLevel /
> >   getMiPOrientationStatus / getMiPStatus / getWeight /
> >   resetOdomemeter / getOdometer / setGestureRadarMode /
> >   getRadarResponsecontinousDriveForwardUntilRadar / setVolume /
> >   getVolume . Radar and Odometer modes seem to conflict at the moment.
> > - First update to vlimits original code. Added charReadReply to read
> >   notifications from mip back to the client. Added continuous drive
> >   methods
> >   stopDrive/continuousDriveForward/continuousTurnRight/continuousTurnLeft/continuousDriveBackward.
> >   continuousTurnRight/continuousTurnLeft not working yet. Added
> >   setChestLed / getChestLed / getBatteryLevel /
> >   getMiPOrientationStatus / getMiPStatus / getWeight /
> >   resetOdomemeter / getOdometer / setGestureRadarMode /
> >   getRadarResponsecontinousDriveForwardUntilRadar / setVolume /
> >   getVolume . Radar and Odometer modes seem to conflict at the moment.
> > - Modified continous drive code. Looks like it might now work.
> >   Renamed mip_test_continous_drive_gui. Added
> >   mip_test_continuous_drive.py mip_test_radar_continuous_drive.py
> >   example programs.
> > - Improved continuous movement code. Written new methods
> >   continuousDrive and continuousCarzyDrive, which are more logical
> >   interfaces to continuous movement. Written new test interface
> >   mip_test_continuous_drive_gui2.py which seems a nicer interface to
> >   drive MiP.
> > - Added more API to mippy library. Started mip_explorer_gui.py.
> > - mip_explorer_gui.py improvements.
> > - More mip_explorer_gui.py changes.
> > - Added Telemetry window.
> > - Improved formatting of Telemetry data in ip_explorer_gui.py.
> > - Added clap recognition to mippy API. Added mip_test_clap.py
> >   example test program.
> > - Added mip_test_eyes.py test program to test eyes. Updated mippy
> >   comments. Added eye dialog to mip_explorer_gui.py.
> >   
> >   ```
> >   File Changes
> >   ```
> > - _A_ src/examples/**init**.py
> >   https://github.com/vlimit/mip/pull/1/files#diff-0 (0)
> > - _A_ src/examples/mip_explorer_gui.py
> >   https://github.com/vlimit/mip/pull/1/files#diff-1 (632)
> > - _A_ src/examples/mip_get_volume.py
> >   https://github.com/vlimit/mip/pull/1/files#diff-2 (27)
> > - _A_ src/examples/mip_set_volume.py
> >   https://github.com/vlimit/mip/pull/1/files#diff-3 (31)
> > - _A_ src/examples/mip_test_clap.py
> >   https://github.com/vlimit/mip/pull/1/files#diff-4 (37)
> > - _A_ src/examples/mip_test_continuous_drive.py
> >   https://github.com/vlimit/mip/pull/1/files#diff-5 (73)
> > - _A_ src/examples/mip_test_continuous_drive_gui.py
> >   https://github.com/vlimit/mip/pull/1/files#diff-6 (75)
> > - _A_ src/examples/mip_test_continuous_drive_gui2.py
> >   https://github.com/vlimit/mip/pull/1/files#diff-7 (61)
> > - _A_ src/examples/mip_test_eyes.py
> >   https://github.com/vlimit/mip/pull/1/files#diff-8 (41)
> > - _A_ src/examples/mip_test_get_battery_level.py
> >   https://github.com/vlimit/mip/pull/1/files#diff-9 (25)
> > - _A_ src/examples/mip_test_get_chest_led.py
> >   https://github.com/vlimit/mip/pull/1/files#diff-10 (29)
> > - _A_ src/examples/mip_test_get_odometer.py
> >   https://github.com/vlimit/mip/pull/1/files#diff-11 (25)
> > - _A_ src/examples/mip_test_get_orientation.py
> >   https://github.com/vlimit/mip/pull/1/files#diff-12 (28)
> > - _A_ src/examples/mip_test_get_weight.py
> >   https://github.com/vlimit/mip/pull/1/files#diff-13 (28)
> > - _A_ src/examples/mip_test_gui.py
> >   https://github.com/vlimit/mip/pull/1/files#diff-14 (104)
> > - _A_ src/examples/mip_test_odometer.py
> >   https://github.com/vlimit/mip/pull/1/files#diff-15 (39)
> > - _A_ src/examples/mip_test_radar_continuous_drive.py
> >   https://github.com/vlimit/mip/pull/1/files#diff-16 (30)
> > - _A_ src/examples/mip_test_sound.py
> >   https://github.com/vlimit/mip/pull/1/files#diff-17 (134)
> > - _A_ src/examples/movement_canvas.py
> >   https://github.com/vlimit/mip/pull/1/files#diff-18 (138)
> > - _M_ src/mippy/**init**.py
> >   https://github.com/vlimit/mip/pull/1/files#diff-19 (553)
> >   
> >   ```
> >   Patch Links:
> >   ```
> > - https://github.com/vlimit/mip/pull/1.patch
> > - https://github.com/vlimit/mip/pull/1.diff
> > 
> > —
> > Reply to this email directly or view it on GitHub 
> > https://github.com/vlimit/mip/pull/1.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vlimit/mip/pull/1#issuecomment-76525455

## 

---

  Chris Mottram                          |
  Liverpool Telescope Programmer.        |
  Liverpool John Moores University,      | email: C.Mottram@ljmu.ac.uk
  Astrophysics Research Institute,       | phone: (0151) 904 6591
  IC2, Liverpool Science Park,           |

##   146 Brownlow Hill, Liverpool, L3 5RF   | www:   www.astro.ljmu.ac.uk

**Pull request merged**
